general {
    disable_loading_bar = true
    hide_cursor = true
    no_fade_in = false
    no_fade_out = false
    ignore_empty_input = true
}

background {
    monitor =
    path = /home/veejh/.local/share/wallpapers/Ant-Dark-wallpapers/Ant-Dark.jpg
    blur_passes = 2
    blur_size = 4
    brightness = 0.6
}

shape {
    monitor =
    size = 380, 1
    color = rgba(fabd2f88)
    position = 0, 80
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 380, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.2
    outer_color = rgba(fabd2fff)
    inner_color = rgba(282828ff)
    font_color = rgba(ebdbb2ff)
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = <i>password</i>
    fail_color = rgba(fb4934ff)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300
    check_color = rgba(fabd2fff)
    position = 0, 40
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgba(fabd2fff)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 180
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %B %d"
    color = rgba(d5c4a1ff)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, 100
    halign = center
    valign = center
}
